aosedge/meta-aos

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-dnsname/aos-dnsname.bb
recipes-aos/aos-firewall/aos-firewall.bb
recipes-aos/aos-iamanager/aos-iamanager_git.bb
recipes-aos/aos-servicemanager/aos-servicemanager_git.bb
recipes-aos/aos-updatemanager/aos-updatemanager_git.bb
recipes-aos/aos-vis/aos-vis_git.bb
recipes-aos/telemetry-emulator/telemetry-emulator.bb

Signed-off-by: Yevgen Abramov <eabramov84@gmail.com>

[all] Change repo url in Aos core recipes

---

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-dnsname/aos-dnsname.bb
recipes-aos/aos-firewall/aos-firewall.bb
recipes-aos/aos-iamanager/aos-iamanager_git.bb
recipes-aos/aos-servicemanager/aos-servicemanager_git.bb
recipes-aos/aos-updatemanager/aos-updatemanager_git.bb
recipes-aos/aos-vis/aos-vis_git.bb
recipes-aos/libvis/libvis_git.bb
recipes-aos/telemetry-emulator/telemetry-emulator.bb

Move all Aos components to https protocol

---

classes/rootfs-image-generator.bbclass

Signed-off-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>

[rootfs-generator] Add SELinux labeling for update image

---

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-iamanager/aos-iamanager_git.bb
recipes-aos/aos-updatemanager/aos-updatemanager_git.bb
recipes-aos/aos-vis/aos-vis_git.bb

Freeze Aos component revision for R5.2.1

---

classes/rootfs-image-generator.bbclass

[rootfs-image-generator] Add policycoreutils-native only for selinux

---

recipes-core/initrdscripts/initramfs-framework/aosupdate

[aosupdate] Add squashfs mount option in order to load squashfs module

---

recipes-aos/aos-setupdisk/files/setupdisk.sh

Add commands for disk setup. It now supports "create" to create Aos disks and
"delete" to deletes Aos disks.

[aos-setupdisk] Add create and delete commands

---

classes/layer-generator.bbclass

Signed-off-by: Mykola Solianko <mykola_solianko@epam.com>

[layer] Add script for prepare whiteouts

---

recipes-extended/iptables/files/iptables.rules
recipes-extended/iptables/iptables_%.bbappend

Signed-off-by: Mykola Solianko <mykola_solianko@epam.com>

Add recipes for add iptables rules

---

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-dnsname/aos-dnsname.bb
recipes-aos/aos-firewall/aos-firewall.bb
recipes-aos/aos-iamanager/aos-iamanager_git.bb
recipes-aos/aos-servicemanager/aos-servicemanager_git.bb
recipes-aos/aos-updatemanager/aos-updatemanager_git.bb
recipes-aos/aos-vis/aos-vis_git.bb

Freeze Aos component revision for R6.0.0

---

recipes-aos/aos-dnsname/aos-dnsname.bb
recipes-aos/aos-firewall/aos-firewall.bb

[aos-cni-pugins] Use GO_BUILD_BINDIR to get valid bin path

---

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-servicemanager/aos-servicemanager_git.bb
recipes-aos/aos-updatemanager/aos-updatemanager_git.bb
recipes-aos/telemetry-emulator/telemetry-emulator.bb

Freeze Aos component revision for R6.0.1

---

recipes-devtools/go/go-1.18.2.inc
recipes-devtools/go/go/0008-fix-filter-compile-flags.patch

[go-1.18] Add patch to fix go build

---

recipes-devtools/go/go-1.18.2.inc
recipes-devtools/go/go/0008-fix-filter-compile-flags.patch

MR Develop to main R6.0.2

---

recipes-aos/aos-provfinish/files/provfinish.sh

[provfinish] Add sync to flush all changes

---

recipes-core/initrdscripts/initramfs-framework_%.bbappend

[initramfs] Add recommended modules for aosupdate script

---

recipes-aos/aos-updatemanager/aos-updatemanager_git.bb

Signed-off-by: Yevgen Abramov <yevgen_abramov@epam.com>

[um] Update revision for R7.0.2 hotfix

---

scripts/custom_yocto.py

For crating filesystem layers
This script designed for use with moulin and build custom bitbake target

Added custom-yocto.py script

---

classes/rootfs-image-generator.bbclass
scripts/bitbake.py
scripts/fota_builder.py

Put all rootfs FOTA tasks under fakeroot and execute cleanall before creating rootfs image.

[rootfs-image-generator] Make all rootfs subtask under fakeroot

---

recipes-core/base-files/base-files_%.bbappend

10 sec is not enough on slow vm.

[fstab] Change Aos disks timeout to 30 sec

---

classes/layer-generator.bbclass

We should use TARGET_ARCH variable for setting layer architecture.

[layer-generator] Fix architecture variable

---

recipes-core/images/aos-image.inc

It is required to be aligned with layers base image.

[aos-image] Put shared base rootfs under ${AOS_BASE_IMAGE}-${MACHINE}

---

recipes-aos/aos-communicationmanager/aos-communicationmanager_git.bb
recipes-aos/aos-communicationmanager/files/aos_communicationmanager.cfg

Fixes the next errors:
Jul 30 11:38:22 main aos_communicati[852]: time="2024-07-30 11:38:22.108" level=error msg="Update failure status: message:\"Head \\\"http://:8092/9JLmBIcDaFRxJT_l0hkdL7ePTUyy-8Wn1GWn-O-jcx0=\\\": dial tcp :8092: connect: connection refused [github.com/aosedge/aos_common/image.Download:115]\""
Jul 30 11:38:22 secondary aos_updatemanag[801]: time="2024-07-30 11:38:22.107" level=error msg="Component error: Head \"http://:8092/9JLmBIcDaFRxJT_l0hkdL7ePTUyy-8Wn1GWn-O-jcx0=\": dial tcp :8092: connect: connection refused [github.com/aosedge/aos_common/image.Download:115]" id=vm-dev-multinode-1.0-secondary-boot_3137b8dc935b41038e07d69d56e5de5d

[communicationmanager] Fix file server URL(s)

---

classes/rootfs-image-generator.bbclass

Current diff analyzer doesn't properly handle spaces in file names. Fix handling item names with spaces.

Fix inc fota generation

---

recipes-support/poco/poco_%.bbappend

This commit should be deleted once the issue if fixed in yocto.

[recipes-support] Fix poco URL after moving to main branch
